export const GOOGLE_API_KEY = 'AIzaSyB5mDO8PVFhFjfmhIAlobiNbMMsYlknTos';
export const API_URL = 'https://api.nfcpoint.ru';

export const GET_CITIES_SUGGESTIONS_REQUEST = 'GET_CITIES_SUGGESTIONS_REQUEST';
export const GET_CITIES_SUGGESTIONS_SUCCESS = 'GET_CITIES_SUGGESTIONS_SUCCESS';

export const GET_PICKPOINTS_REQUEST = 'GET_PICKPOINTS_REQUEST';
export const GET_PICKPOINTS_SUCCESS = 'GET_PICKPOINTS_SUCCESS';

export const ADD_FILE_REQUEST = 'ADD_FILE_REQUEST';
export const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS';

export const DELETE_FILE_REQUEST = 'DELETE_FILE_REQUEST';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';

export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';

export const CALCULATE_DELIVERY_REQUEST = 'CALCULATE_DELIVERY_REQUEST';
export const CALCULATE_DELIVERY_SUCCESS = 'CALCULATE_DELIVERY_SUCCESS';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';